services:
  - type: web
    name: whatsapp-automation-server
    env: node
    region: ohio
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    healthCheckPath: /api/health
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production

databases:
  - name: whatsapp-automation-db
    region: ohio
    plan: free
    databaseName: whatsappdb
    user: whatsappuser
    ipAllowList: []